### ISSUE TITLE
[RFC] Yarn 2

### ISSUE THREAD

**Issue by Thomazella** [FotonTech/golden-stack#16]
Currently golden stack has no app, which enables usage of yarn 2.

However the team has plans to add an app to golden-stack.

Options
- Make golden stack web only and use yarn 2, until react-native supports yarn 2
- Add app, fork repo for yarn 2 version

Basically: What's more valuable in the repo, app or yarn 2?

**Comment by jgcmarins** [comment]
Golden Stack idea is to show how easy we share code between web and app with Relay and GraphQL.
So I think it's better to keep yarn 1 and bring back app (which was removed [here](https://github.com/FotonTech/golden-stack/pull/7))

**Comment by rthomazel** [comment]
Yeah so, after trying yarn 2 myself it still needs some tweaking to work properly with other tools. Think it makes sense to close
