### ISSUE TITLE
can't run web-razzle start

### ISSUE THREAD

**Issue by sibelius** [FotonTech/golden-stack#21]
![image](https://user-images.githubusercontent.com/2005841/73620932-cfed1c00-4612-11ea-88ae-59e3ac3b5aaa.png)

Refused to load the image 'http://localhost:7002/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

`yarn start` inside `packages/web-razzle`

some logs
```jsx
 WAIT  Compiling...


✔ Client
  Compiled successfully in 4.24s

✔ Server
  Compiled successfully in 3.03s

ℹ ｢wds｣: Project is running at http://localhost:7002/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /golden-stack/packages/web-razzle
ℹ ｢wds｣: 404s will fallback to /index.html
✅  Server-side HMR Enabled!
🚀 started
```

**Comment by jgcmarins** [comment]
I don't know how to change that but razzle runs in 2 ports.
The server runs on 7002 and the client runs on 7001.

Run again and then open on http://localhost:7001
It should work.
