### ISSUE TITLE
bug on expo-app package

### ISSUE THREAD

**Issue by jgcmarins** [FotonTech/golden-stack#33]
ref #30

![image](https://user-images.githubusercontent.com/5133450/84580366-c471e480-adac-11ea-8f37-f7e7113ba6f7.png)

### How to reproduce?
- run `yarn startup`

**Comment by lucasfloriani** [comment]
As @mauriciord pointed, `expo-yarn-workspaces` won't work in Windows, the note about this is in [here](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces#expo-yarn-workspaces)
Maybe we can add a warning about that in the main README file, what do you think?

**Comment by renanmav** [comment]
https://github.com/expo/expo/commit/5d64834bf3997dd78dbce5068e1c13e08e3333b6

**Comment by sibelius** [comment]
Why?

**Comment by renanmav** [comment]
https://github.com/expo/expo/issues/6983

**Comment by jgcmarins** [comment]
My suggestion: get rid of expo.
Use pure React Native so we can support several platforms, or, at least Mac, Linux and Windows

**Comment by lucasfloriani** [comment]
Maybe docker can be an alternative to this? I didn't use docker to much to affirm this but maybe it can work

**Comment by mauriciord** [comment]
I don't even know if this package (`expo-yarn-workspaces`) is still necessary. Did you try without it @lucasfloriani ?

**Comment by mauriciord** [comment]
Did you try?
https://github.com/expo/expo/issues/6983#issuecomment-586900713

**Comment by lucasfloriani** [comment]
> Did you try?
> [expo/expo#6983 (comment)](https://github.com/expo/expo/issues/6983#issuecomment-586900713)

I tried it but didn't work, gonna check now if this package is still needed.

**Comment by lucasfloriani** [comment]
#34 Is waiting for reviews \o

**Comment by jgcmarins** [comment]
looks like #34 fix this one
thanks
